#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save
#
source "/home/brice/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh"
source "/home/brice/.zgen/jimmijj/zsh-syntax-highlighting-master//zsh-syntax-highlighting.plugin.zsh"
source "/home/brice/.zgen/tarruda/zsh-autosuggestions-master//autosuggestions.plugin.zsh"
source "/home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "/home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh"
source "/home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/web-search/web-search.plugin.zsh"
source "/home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/brice/.zgen/robbyrussell/oh-my-zsh-master /home/brice/.zgen/jimmijj/zsh-syntax-highlighting-master /home/brice/.zgen/tarruda/zsh-autosuggestions-master /home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/git /home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo /home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/web-search /home/brice/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found /home/brice/.zgen/zsh-users/zsh-completions-master/src ${fpath})
